
 UPDATE P SET P.AGENTSOCIALID = AG.FULLNAME
 from  PAX00000 p INNER join smx00300  ag on 
 -- ag.FULLNAME = p.AGENTSOCIALID and 
     REPLACE(rtrim(ltrim(isnull(ag.NOMBRE1,'')))  +''+ rtrim(ltrim(isnull(ag.NOMBRE2,'')))+''+  rtrim(ltrim(isnull(ag.APELLIDO1,'')))  +''+  rtrim(ltrim(isnull(ag.APELLIDO2,''))),' ','') 
	  = REPLACE(rtrim(ltrim(isnull(P.AGENTSOCIALID,''))),' ','')
 and p.RECORDID > 0

 
  UPDATE PAX00000   SET  AGENTSOCIALID= 'LUZ MAGALY CID DE LA CRUZ'                 WHERE AGENTSOCIALID = 'LUZ MAGALY CID DE LA CRUZ DE SANTOS' 
  UPDATE PAX00000   SET  AGENTSOCIALID= 'THELMA BIENVENIDA PEREZ SENCION'           WHERE AGENTSOCIALID = 'THELMA PEREZ'
   UPDATE PAX00000   SET  AGENTSOCIALID= 'YAKAYRA   MONTERO CAROLINA ORTIZ MONTERO' WHERE AGENTSOCIALID = 'YAKAYRA CAROLINA ORTIZ MONTERO'
   UPDATE PAX00000   SET  AGENTSOCIALID= 'ZULEICA  RIVAS REYES'						WHERE AGENTSOCIALID = 'ZULEICA RIVAS'

      UPDATE  PAX00000  SET AGENTSOCIALID=''  where  RECORDID > 0
   AND ROWGUID NOT IN 
   (select  P.ROWGUID 
 from  PAX00000 p INNER join smx00300  ag on 
   ag.FULLNAME = p.AGENTSOCIALID
   AND AG.ROWSGXID = P.ROWSGXID 
   AND AG.ESPECIALIDADID ='C0C9C39F-6231-4BC2-8791-8F934AD96D7C'
 and p.RECORDID > 0)
 AND AGENTSOCIALID='ARELIS GARCÍA GARCÍA'
 