SELECT        REFGUID, MEDID, TERID, ENFID, ORIGENID, FECHAINI, FECHAFIN, HORAINI, HORAFIN, DIA, OBSERVACION, ASISTIOULTCITA, CITAESTATUS, HORAORDINAL, ROWIDX, ROWGUID, ROWCDTE, ROWMDTE, 
                         ROWUSERID, ROWSGXID, TERAPIAINI, TERAPIAFIN, DETALLES, TIPO, TIPOGUID, DETTERAPEUTA, DETAUSENCIATERAPEUTA
FROM            SMX00500
WHERE        (REFGUID = 'CAID-SD-00191') AND (YEAR(FECHAFIN) = 2017) AND (ORIGENID = 'CAID-SD-HISCL-12') AND (FECHAINI = '2017-09-26 00:00:00.000')
ORDER BY FECHAFIN DESC