/*
SELECT P.ROWUSERID,   P.ESTATUS, 
* 
-- into _PACIENTESSERVICIOSOCIALTMP3 
FROM PAX00000 P , _PACIENTESSERVICIOSOCIALTMP2 TMP   WHERE
TMP.EXP# = P.RECORDID
-- AND TMP.CODIGOAGENTE = U.USR
and p.ROWSGXID='CAID-SD'
order by tmp.exp#

*/

SELECT T.* FROM _PACIENTESSERVICIOSOCIALTMP2 T, SMX30051 E
WHERE E.NOMBRE = T.ESTATUS

UPDATE T SET T.CODIGOESTATUS = E.ROWGUID
FROM _PACIENTESSERVICIOSOCIALTMP2 T, SMX30051 E
WHERE E.NOMBRE = T.ESTATUS
SELECT T.* FROM _PACIENTESSERVICIOSOCIALTMP2 T
-- TRUNCATE TABLE _PACIENTESSERVICIOSOCIALTMP2

----------------------------------------------

SELECT * INTO PAX00000_Back2072017 FROM PAX00000 
select * from _PACIENTESSERVICIOSOCIALTMP 
select * from _PACIENTESSERVICIOSOCIALTMP2 --2279
select * from pax00000 where ROWSGXID='CAID-SD' -- 2422

-- select * from _PACIENTESSERVICIOSOCIALTMP2 where  Estatus='No Criterio Diagnóstico' 

----------------------------------------------------

UPDATE P  SET -- P.ROWUSERID =  U.ROWGUID, 
		  P.ESTATUS= TMP.CODIGOESTATUS

  FROM PAX00000 P , _PACIENTESSERVICIOSOCIALTMP2 TMP  WHERE
TMP.EXP# = P.RECORDID 
AND P.ROWSGXID='CAID-SD' 

select p.AGENTSOCIALID, tmp.[agente social]
  FROM PAX00000 P , _PACIENTESSERVICIOSOCIALTMP2 TMP  WHERE
TMP.EXP# = P.RECORDID 
AND P.ROWSGXID='CAID-SD' 

select * from _PACIENTESSERVICIOSOCIALTMP2

 
 SELECT * INTO PAX00000 FROM PAX00000_12052017


UPDATE p set p.AGENTSOCIALID =  tmp.[agente social]

FROM PAX00000 P , 
   _PACIENTESSERVICIOSOCIALTMP2 TMP  WHERE
TMP.EXP# = P.RECORDID 
AND P.ROWSGXID='CAID-SD' 
