 /*
 EXEC PAX00000S4 @NOMBRE = N''
			   ,@ROWSGXID = N'CAID-SD'
			   ,@TOP = N'100'

EXEC PAX00300SI @NOMBRE = N'PRUEBA 1'
			   ,@REFGUID = N'B25A276B-4E83-48E4-A348-BB9517C0E4A4'
			   ,@ADMITIDOID = N'1'
			   ,@ROWGUID = N'9D8F70F5-D367-4805-9618-AFB4C68BDB61'
			   ,@ROWUSERID = N'64C361FA-686D-4714-ACE2-028E4A3C1F25'
			   ,@ROWSGXID = N'CAID-SD'

SELECT * FROM [PAX00300] WHERE ROWGUID = @ROWGUID AND ROWSGXID = @ROWSGXID
SELECT * FROM PAX00000 WHERE ROWSGXID = 'CAID-SD' AND RECORDID = 1592

SELECT * FROM PAX00000 WHERE ROWSGXID = 'CAID-SD' and fullname like '%ANGEL URIEL VASQUEZ%'

*/

 
 
 -- SELECT ROWGUID,*   FROM PAX00000 where fullname like '%diego ernesto%'
 -- select * from SGX00100 where ROWGUID ='64C361FA-686D-4714-ACE2-028E4A3C1F25'


USE CAID
 GO

DECLARE  	
	@NOMBRE		varchar(50)='DIEGO ERNESTO RAMIREZ CRUZ',
	@REFGUID	varchar(50) ='5C422BB0-AB17-4701-AFFE-89A55D9EB68E',
	@RECORDID1   varchar(50)='1974',
	@ADMITIDOID varchar(50) = '1',
	@ROWGUID	varchar(50) =newid(),
	@ROWUSERID	varchar(50)='64C361FA-686D-4714-ACE2-028E4A3C1F25',
	@ROWSGXID	varchar(50)='CAID-SD'
 

DECLARE @QRY NVARCHAR(4000),
		@TBL NVARCHAR(100) = 'PAX00300'


IF NOT EXISTS ( SELECT * FROM [PAX00300] WHERE ROWGUID = @ROWGUID AND ROWSGXID = @ROWSGXID )
	BEGIN
	DECLARE	@RECORDID int = 0, 
			@ADMITIDOCOMO varchar(100),
			@ADMITE bit

	SELECT @ADMITE = ADMITE, @ADMITIDOCOMO = NOMBRE FROM SMX30017 WHERE ROWGUID = @ADMITIDOID

	IF(@ADMITE = 1)
		BEGIN

		--SELECT @RECORDID = ISNULL(MAX(RECORDID),0)+1 FROM PAX00000 WHERE ROWSGXID = @ROWSGXID 
		SET @RECORDID = @RECORDID1
		END
	ELSE
		BEGIN

		SET @RECORDID = -1

		END


	UPDATE PAX00000 SET RECORDID = @RECORDID, ESTATUS='00000000-0000-0000-0000-000000000001' /*PROCESO DE EVALUACION*/ WHERE ROWSGXID = @ROWSGXID AND  ROWGUID = @REFGUID
	and RECORDID =0

	INSERT INTO [PAX00300]
	(
	 [NOMBRE], [REFGUID], [RECORDID], [ADMITIDOID], [ADMITIDOCOMO]
	,[ROWGUID],[ROWCDTE],[ROWMDTE], [ROWUSERID]
	,[ROWSGXID]
	)
	VALUES
	(
	 @NOMBRE, @REFGUID, @RECORDID, @ADMITIDOID, @ADMITIDOCOMO
	, @ROWGUID, GETDATE(), GETDATE(), @ROWUSERID
	,@ROWSGXID
	)

	DECLARE @XXESPGUID VARCHAR(50),
			@GUIDOBJ   VARCHAR(50),
			@ACTGUID   VARCHAR(50)
	

SET @XXESPGUID = 'CAID-SD-HISCL-01'
SET @GUIDOBJ   = NEWID()
SET @ACTGUID   = NEWID()
	
IF NOT EXISTS(SELECT * FROM [HCX00300] WHERE [REFGUID] = @REFGUID AND [ESPECILIDADGUID] = @XXESPGUID)
BEGIN	
	INSERT INTO [HCX00300]
           ([REFGUID]
           ,[NOMBRE]
           ,[ROWGUID]
           ,[ROWCDTE]
           ,[ROWMDTE]
           ,[ROWUSERID]
           ,[ROWSGXID]
           ,[ESPECILIDADGUID]
           ,[OBJETIVOGUID])
	SELECT	[REFGUID]			= @REFGUID
           ,[NOMBRE]			= 'CONSULTA'
           ,[ROWGUID]			= @GUIDOBJ
           ,[ROWCDTE]			= GETDATE()
           ,[ROWMDTE]			= GETDATE()
           ,[ROWUSERID]			= 'SYSTEM'
           ,[ROWSGXID]			= @ROWSGXID
           ,[ESPECILIDADGUID]	= @XXESPGUID
           ,[OBJETIVOGUID]      = @GUIDOBJ

	INSERT INTO [CAID].[dbo].[HCX00300_D]
			   ([OBJID]
			   ,[NOMBRE]
			   ,[COMPLETADO]
			   ,[ROWGUID]
			   ,[ROWCDTE]
			   ,[ROWMDTE]
			   ,[ROWUSERID]
			   ,[ROWSGXID]
			   ,[ACTIVIDADGUID])
		SELECT	[OBJID]			= @GUIDOBJ
			   ,[NOMBRE]		= 'CONSULTA MEDICA'
			   ,[COMPLETADO]	= 0	
			   ,[ROWGUID]		= @ACTGUID
			   ,[ROWCDTE]		= GETDATE()
			   ,[ROWMDTE]		= GETDATE()
			   ,[ROWUSERID]		= 'SYSTEM'
			   ,[ROWSGXID]		= @ROWSGXID
			   ,[ACTIVIDADGUID] = @ACTGUID
END


SET @XXESPGUID = 'CAID-SD-HISCL-03'
SET @GUIDOBJ   = NEWID()
SET @ACTGUID   = NEWID()
	
IF NOT EXISTS(SELECT * FROM [HCX00300] WHERE [REFGUID] = @REFGUID AND [ESPECILIDADGUID] = @XXESPGUID)
BEGIN	
	INSERT INTO [HCX00300]
           ([REFGUID]
           ,[NOMBRE]
           ,[ROWGUID]
           ,[ROWCDTE]
           ,[ROWMDTE]
           ,[ROWUSERID]
           ,[ROWSGXID]
           ,[ESPECILIDADGUID]
           ,[OBJETIVOGUID])
	SELECT	[REFGUID]			= @REFGUID
           ,[NOMBRE]			= 'CONSULTA'
           ,[ROWGUID]			= @GUIDOBJ
           ,[ROWCDTE]			= GETDATE()
           ,[ROWMDTE]			= GETDATE()
           ,[ROWUSERID]			= 'SYSTEM'
           ,[ROWSGXID]			= @ROWSGXID
           ,[ESPECILIDADGUID]	= @XXESPGUID
           ,[OBJETIVOGUID]      = @GUIDOBJ

	INSERT INTO [CAID].[dbo].[HCX00300_D]
			   ([OBJID]
			   ,[NOMBRE]
			   ,[COMPLETADO]
			   ,[ROWGUID]
			   ,[ROWCDTE]
			   ,[ROWMDTE]
			   ,[ROWUSERID]
			   ,[ROWSGXID]
			   ,[ACTIVIDADGUID])
		SELECT	[OBJID]			= @GUIDOBJ
			   ,[NOMBRE]		= 'CONSULTA MEDICA'
			   ,[COMPLETADO]	= 0	
			   ,[ROWGUID]		= @ACTGUID
			   ,[ROWCDTE]		= GETDATE()
			   ,[ROWMDTE]		= GETDATE()
			   ,[ROWUSERID]		= 'SYSTEM'
			   ,[ROWSGXID]		= @ROWSGXID
			   ,[ACTIVIDADGUID] = @ACTGUID
END



SET @XXESPGUID = 'CAID-SD-HISCL-05'
SET @GUIDOBJ   = NEWID()
SET @ACTGUID   = NEWID()

	
IF NOT EXISTS(SELECT * FROM [HCX00300] WHERE [REFGUID] = @REFGUID AND [ESPECILIDADGUID] = @XXESPGUID)
BEGIN	
	INSERT INTO [HCX00300]
           ([REFGUID]
           ,[NOMBRE]
           ,[ROWGUID]
           ,[ROWCDTE]
           ,[ROWMDTE]
           ,[ROWUSERID]
           ,[ROWSGXID]
           ,[ESPECILIDADGUID]
           ,[OBJETIVOGUID])
	SELECT	[REFGUID]			= @REFGUID
           ,[NOMBRE]			= 'CONSULTA'
           ,[ROWGUID]			= @GUIDOBJ
           ,[ROWCDTE]			= GETDATE()
           ,[ROWMDTE]			= GETDATE()
           ,[ROWUSERID]			= 'SYSTEM'
           ,[ROWSGXID]			= @ROWSGXID
           ,[ESPECILIDADGUID]	= @XXESPGUID
           ,[OBJETIVOGUID]      = @GUIDOBJ

	INSERT INTO [CAID].[dbo].[HCX00300_D]
			   ([OBJID]
			   ,[NOMBRE]
			   ,[COMPLETADO]
			   ,[ROWGUID]
			   ,[ROWCDTE]
			   ,[ROWMDTE]
			   ,[ROWUSERID]
			   ,[ROWSGXID]
			   ,[ACTIVIDADGUID])
		SELECT	[OBJID]			= @GUIDOBJ
			   ,[NOMBRE]		= 'CONSULTA MEDICA'
			   ,[COMPLETADO]	= 0	
			   ,[ROWGUID]		= @ACTGUID
			   ,[ROWCDTE]		= GETDATE()
			   ,[ROWMDTE]		= GETDATE()
			   ,[ROWUSERID]		= 'SYSTEM'
			   ,[ROWSGXID]		= @ROWSGXID
			   ,[ACTIVIDADGUID] = @ACTGUID
END

SET @XXESPGUID = 'CAID-SD-HISCL-16'
SET @GUIDOBJ   = NEWID()
SET @ACTGUID   = NEWID()

	
IF NOT EXISTS(SELECT * FROM [HCX00300] WHERE [REFGUID] = @REFGUID AND [ESPECILIDADGUID] = @XXESPGUID)
BEGIN	
	INSERT INTO [HCX00300]
           ([REFGUID]
           ,[NOMBRE]
           ,[ROWGUID]
           ,[ROWCDTE]
           ,[ROWMDTE]
           ,[ROWUSERID]
           ,[ROWSGXID]
           ,[ESPECILIDADGUID]
           ,[OBJETIVOGUID])
	SELECT	[REFGUID]			= @REFGUID
           ,[NOMBRE]			= 'CONSULTA'
           ,[ROWGUID]			= @GUIDOBJ
           ,[ROWCDTE]			= GETDATE()
           ,[ROWMDTE]			= GETDATE()
           ,[ROWUSERID]			= 'SYSTEM'
           ,[ROWSGXID]			= @ROWSGXID
           ,[ESPECILIDADGUID]	= @XXESPGUID
           ,[OBJETIVOGUID]      = @GUIDOBJ

	INSERT INTO [CAID].[dbo].[HCX00300_D]
			   ([OBJID]
			   ,[NOMBRE]
			   ,[COMPLETADO]
			   ,[ROWGUID]
			   ,[ROWCDTE]
			   ,[ROWMDTE]
			   ,[ROWUSERID]
			   ,[ROWSGXID]
			   ,[ACTIVIDADGUID])
		SELECT	[OBJID]			= @GUIDOBJ
			   ,[NOMBRE]		= 'CONSULTA MEDICA'
			   ,[COMPLETADO]	= 0	
			   ,[ROWGUID]		= @ACTGUID
			   ,[ROWCDTE]		= GETDATE()
			   ,[ROWMDTE]		= GETDATE()
			   ,[ROWUSERID]		= 'SYSTEM'
			   ,[ROWSGXID]		= @ROWSGXID
			   ,[ACTIVIDADGUID] = @ACTGUID
END




SET @XXESPGUID = 'CAID-SD-HISCL-09'
SET @GUIDOBJ   = NEWID()
SET @ACTGUID   = NEWID()
	
IF NOT EXISTS(SELECT * FROM [HCX00300] WHERE [REFGUID] = @REFGUID AND [ESPECILIDADGUID] = @XXESPGUID)
BEGIN	
	INSERT INTO [HCX00300]
           ([REFGUID]
           ,[NOMBRE]
           ,[ROWGUID]
           ,[ROWCDTE]
           ,[ROWMDTE]
           ,[ROWUSERID]
           ,[ROWSGXID]
           ,[ESPECILIDADGUID]
           ,[OBJETIVOGUID])
	SELECT	[REFGUID]			= @REFGUID
           ,[NOMBRE]			= 'CONSULTA'
           ,[ROWGUID]			= @GUIDOBJ
           ,[ROWCDTE]			= GETDATE()
           ,[ROWMDTE]			= GETDATE()
           ,[ROWUSERID]			= 'SYSTEM'
           ,[ROWSGXID]			= @ROWSGXID
           ,[ESPECILIDADGUID]	= @XXESPGUID
           ,[OBJETIVOGUID]      = @GUIDOBJ

	INSERT INTO [CAID].[dbo].[HCX00300_D]
			   ([OBJID]
			   ,[NOMBRE]
			   ,[COMPLETADO]
			   ,[ROWGUID]
			   ,[ROWCDTE]
			   ,[ROWMDTE]
			   ,[ROWUSERID]
			   ,[ROWSGXID]
			   ,[ACTIVIDADGUID])
		SELECT	[OBJID]			= @GUIDOBJ
			   ,[NOMBRE]		= 'CONSULTA MEDICA'
			   ,[COMPLETADO]	= 0	
			   ,[ROWGUID]		= @ACTGUID
			   ,[ROWCDTE]		= GETDATE()
			   ,[ROWMDTE]		= GETDATE()
			   ,[ROWUSERID]		= 'SYSTEM'
			   ,[ROWSGXID]		= @ROWSGXID
			   ,[ACTIVIDADGUID] = @ACTGUID
END

SET @XXESPGUID = '1F8CAC37-0F91-4FB2-8D74-063AF752E712'
SET @GUIDOBJ   = NEWID()
SET @ACTGUID   = NEWID()
	
IF NOT EXISTS(SELECT * FROM [HCX00300] WHERE [REFGUID] = @REFGUID AND [ESPECILIDADGUID] = @XXESPGUID)
BEGIN	
	INSERT INTO [HCX00300]
           ([REFGUID]
           ,[NOMBRE]
           ,[ROWGUID]
           ,[ROWCDTE]
           ,[ROWMDTE]
           ,[ROWUSERID]
           ,[ROWSGXID]
           ,[ESPECILIDADGUID]
           ,[OBJETIVOGUID])
	SELECT	[REFGUID]			= @REFGUID
           ,[NOMBRE]			= 'CONSULTA'
           ,[ROWGUID]			= @GUIDOBJ
           ,[ROWCDTE]			= GETDATE()
           ,[ROWMDTE]			= GETDATE()
           ,[ROWUSERID]			= 'SYSTEM'
           ,[ROWSGXID]			= @ROWSGXID
           ,[ESPECILIDADGUID]	= @XXESPGUID
           ,[OBJETIVOGUID]      = @GUIDOBJ

	INSERT INTO [CAID].[dbo].[HCX00300_D]
			   ([OBJID]
			   ,[NOMBRE]
			   ,[COMPLETADO]
			   ,[ROWGUID]
			   ,[ROWCDTE]
			   ,[ROWMDTE]
			   ,[ROWUSERID]
			   ,[ROWSGXID]
			   ,[ACTIVIDADGUID])
		SELECT	[OBJID]			= @GUIDOBJ
			   ,[NOMBRE]		= 'CONSULTA MEDICA'
			   ,[COMPLETADO]	= 0	
			   ,[ROWGUID]		= @ACTGUID
			   ,[ROWCDTE]		= GETDATE()
			   ,[ROWMDTE]		= GETDATE()
			   ,[ROWUSERID]		= 'SYSTEM'
			   ,[ROWSGXID]		= @ROWSGXID
			   ,[ACTIVIDADGUID] = @ACTGUID
END

	END
