

select MONTH(ROWCDTE) AS MES, YEAR(ROWCDTE) AS ANIO, COUNT(*) AS CANTIDAD from PAX00000 WHERE ROWSGXID = 'CAID-STG'
AND CAST(ROWCDTE AS DATE) BETWEEN '2017-04-01' AND '2018-04-30'  AND RECORDID='0'
GROUP BY  MONTH(ROWCDTE) , YEAR(ROWCDTE)
ORDER BY  YEAR(ROWCDTE),  MONTH(ROWCDTE) 


 