

-- cantidad de ninos recibidos
select   DATEPART(year,ROWCDTE) as anio,  ROWSGXID , count(*) as cantidad from PAX00000 
group by DATEPART(year,ROWCDTE) ,  ROWSGXID 
order by ROWSGXID,DATEPART(year,ROWCDTE)  
   

-- cantidad de ninos en recurrentes
SELECT DATEPART(year,P.ROWCDTE) as anio,  P.ROWSGXID , count(DISTINCT P.ROWGUID) as cantidad
  FROM SMX00500 AS CR
  INNER JOIN PAX00000 P ON P.ROWGUID = CR.REFGUID
  LEFT JOIN SMX00300 o ON CR.TERID = o.ROWGUID 
  LEFT JOIN SMX30014 e ON CR.ORIGENID = e.ROWGUID  
  LEFT JOIN SMX30013 es ON o.ESPECIALIDADID = es.ROWGUID
  WHERE CR.TIPO IN ('CR','CG')
  AND CR.ASISTIOULTCITA = 0
  AND CR.CITAESTATUS = 1
  -- AND CONVERT(DATETIME,CONVERT(varchar(10),CR.FECHAINI,127)) >= CONVERT(DATETIME,CONVERT(varchar(10),GETDATE(),127))
  GROUP BY  DATEPART(year,P.ROWCDTE)  ,  P.ROWSGXID
  order by ROWSGXID,DATEPART(year,P.ROWCDTE)  

-- cantidad de egresos.
