
-- CANTIDAD DE NINOS CON TEA ----
select 
P.ROWSGXID AS CENTRO, P.PREDIAGNOSTICODESCRIPCION , 
 (SELECT COUNT(*) FROM vPacienteTodos WHERE RECORDID>0 AND ROWSGXID = P.ROWSGXID) AS  TOTAL_PACIENTE,
Count(*) as TOTAL_CON_TEA  
  from vPacienteTodos P where -- P.ROWSGXID = 'CAID-SD'  and 
 PREDIAGNOSTICODESCRIPCION='TEA' 
 AND  P.RECORDID>0
group by P.ROWSGXID,P.PREDIAGNOSTICODESCRIPCION


-- CANTIDAD DE NINOS CON TEA x RANGO DE EDADES ----

SELECT
	CENTRO = suc.nombre , 
	CASE
		WHEN DATEDIFF(YEAR, P.FNACE, GETDATE()) BETWEEN 0 AND 5 THEN 'DE 0 A 5 AÑOS'
		WHEN DATEDIFF(YEAR, P.FNACE, GETDATE()) BETWEEN 6 AND 10 THEN 'DE 6 A 10 AÑOS'
		ELSE 'MAYOR A 10'
	END AS GRUPO_DE_EDADES
   ,COUNT(*) AS TOTAL_PACIENTE

	FROM -- SMX00500 AS CR  INNER JOIN 
	    PAX00000 P  
		INNER JOIN SGX00000 suc ON suc.rowsgxid = P.rowsgxid
	WHERE  
	--AND CR.ROWSGXID = 'CAID-SD'
	  DATEDIFF(YEAR, P.FNACE, GETDATE()) <=10
	AND P.RECORDID >0
	AND P.PREDIAGNOSTICO = 'A00A2CDA-7D61-4E4A-A95A-7B5DE484422D'
	GROUP BY suc.nombre
			, 
			 CASE
				 WHEN DATEDIFF(YEAR, P.FNACE, GETDATE()) BETWEEN 0 AND 5 THEN 'DE 0 A 5 AÑOS'
				 WHEN DATEDIFF(YEAR, P.FNACE, GETDATE()) BETWEEN 6 AND 10 THEN 'DE 6 A 10 AÑOS'
				 ELSE 'MAYOR A 10'
			 END 

		ORDER BY CENTRO,GRUPO_DE_EDADES


		 
