select  DATEPART(YEAR,D.ROWCDTE) AS ANIO,	
       DATEPART(M,D.ROWCDTE) AS MES,
		V_PACINETE		= SUM( ((D.TARIFACOPAGO)-((D.TARIFACOPAGO)*(C.DESCUENTO/100.00))) * D.TARIFACANT),

		SEGURO			= SUM( D.TARIFACANT*D.TARIFASEGURO )

		  
FROM	FTX00000 M

		INNER JOIN FTX00000_D D ON M.ROWGUID = D.FACTURAID

		INNER JOIN PAX00000 PA ON M.REFGUID = PA.ROWGUID

		INNER JOIN PAX00200 C ON PA.CATEGORIAID = C.ROWGUID

		LEFT JOIN SMX00200 S ON M.ARSID = S.ROWGUID

		LEFT JOIN SMX00201 PL ON M.PLANID = PL.ROWGUID

		LEFT OUTER JOIN SGX00100 U ON U.ROWGUID = M.ROWUSERID

WHERE	 M.ROWSGXID = 'CAID-STG'
		GROUP BY  DATEPART(YEAR,D.ROWCDTE), DATEPART(M,D.ROWCDTE) 
		ORDER BY  DATEPART(YEAR,D.ROWCDTE) DESC ,DATEPART(M,D.ROWCDTE)  DESC 