USE [CAID]
GO
 
ALTER PROCEDURE [dbo].[PR_PACIENTECRONOGRAMA]
@ROWSGXID		varchar(50)
AS 
 
 /*CUANDO INICIO EVALUACION INICIAL*/
 IF OBJECT_ID('tempdb.#PX_EvaluacionInicial') IS NOT NULL  
  DROP TABLE #PX_EvaluacionInicial

select AM.REFGUID, AM.ROWSGXID,MIN(AM.ROWCDTE) AS Fecha
    INTO #PX_EvaluacionInicial
 	FROM		HCL00037 M
				JOIN HCL00000 AM ON M.ACTGUID = AM.ROWGUID
				AND AM.ROWSGXID = M.ROWSGXID
				AND AM.ROWSGXID=@ROWSGXID
group by AM.REFGUID, AM.ROWSGXID
order by AM.ROWSGXID

/*CUANDO INICIO EN UN SERVICIO o Inicio Plan Terapeutico*/
 IF OBJECT_ID('tempdb.#PX_PlanTerapeutico') IS NOT NULL  
  DROP TABLE #PX_PlanTerapeutico

	SELECT	 CR.REFGUID, CR.ROWSGXID, MIN(CR.ROWCDTE) AS Fecha
	into #PX_PlanTerapeutico
	FROM SMX00500 AS CR 
	WHERE CR.TIPO IN ('CR','CG')
	     AND CR.ROWSGXID =   @ROWSGXID   
	group by CR.REFGUID, CR.ROWSGXID
	order by CR.ROWSGXID

SELECT  distinct 
 P.RECORDID,
 P.FULLNAME,  
 C.NOMBRE CATEGORIADESC,
 ESTATUS.NOMBRE AS ESTATUSDESCRIPCION,
 ARS.NOMBRE AS ARSDESCRIPCION,
 P.ROWGUID AS IDPACIENTE,
 CASE P.RECORDID
     WHEN 0 THEN 'PENDIENTE'
     WHEN -1 THEN 'RECHAZADO'
     ELSE 'ACEPTADO'
 END AS ESTATUSRECORID,  
 DATEDIFF(YEAR, P.FNACE, getdate()) AS Edad,

  (SELECT EDAD FROM dbo.GetDateYearsMonthsDays(P.FNACE, getdate())) AS EdadMeses ,
   p.ROWCDTE, 
   isnull(FORMAT (min(AD.ROWCDTE), 'yyyy/MM/dd'),FORMAT (min(P.ROWCDTE), 'yyyy/MM/dd')) as Fechaadmision,
   FORMAT (min(RA.fechaini), 'dd/MM/yyyy') as FechaRutaBasica, 
   DATEDIFF(day, P.ROWCDTE,  AD.ROWCDTE ) AS Dias_ParaserAdmitido,
   DATEDIFF(day, P.ROWCDTE, min(RA.fechaini) ) AS Dias_ParaEntrarRutaBasica,
   FORMAT (EVInicial.FECHA, 'dd/MM/yyyy')  AS FechaEvaluacionInicial,
   FORMAT (PlanTera.FECHA, 'dd/MM/yyyy')  AS FechaPlanTerapeutico,
   CASE WHEN ESTATUSPX.ROWGUID ='91646783-A9F4-415E-A6E8-CF6BC3185E00'  THEN FORMAT (P.ROWMDTE, 'dd/MM/yyyy')  ELSE NULL END AS FechaEgreso
 
FROM PAX00000 P
LEFT JOIN PAX00200 C ON P.CATEGORIAID = C.ROWGUID
LEFT JOIN SGX00100 U ON p.ROWUSERID = U.ROWGUID AND U.ROWSGXID = P.ROWSGXID
LEFT JOIN SMX30051 ESTATUS ON /*ESTATUS.ROWSGXID = P.ROWSGXID AND*/ P.ESTATUS = ESTATUS.ROWGUID
LEFT JOIN SMX00201 ARS ON /*ARS.ROWSGXID = P.ROWSGXID AND */ P.ARSID = ARS.ARSID 
LEFT JOIN  PAX00300 AD ON P.ROWGUID = AD.REFGUID AND P.ROWSGXID = AD.ROWSGXID
LEFT JOIN  SMX00500 RA ON RA.REFGUID = P.ROWGUID AND P.ROWSGXID = RA.ROWSGXID --AND RA.TIPO = 'RA'
LEFT JOIN #PX_EvaluacionInicial EVInicial ON EVInicial.REFGUID = P.ROWGUID AND EVInicial.ROWSGXID = P.ROWSGXID
LEFT JOIN #PX_PlanTerapeutico PlanTera ON PlanTera.REFGUID = P.ROWGUID AND PlanTera.ROWSGXID = P.ROWSGXID
LEFT JOIN SMX30051 ESTATUSPX ON ESTATUSPX.ROWGUID ='91646783-A9F4-415E-A6E8-CF6BC3185E00' /*EGRESADOS*/ AND P.ESTATUS = ESTATUSPX.ROWGUID
WHERE   P.ROWSGXID=@ROWSGXID AND P.RECORDID>0
 GROUP BY P.RECORDID, P.FULLNAME , C.NOMBRE,  ESTATUS.NOMBRE,  ARS.NOMBRE, P.ROWGUID, P.FNACE,p.ROWCDTE, AD.ROWCDTE, EVInicial.fecha, PlanTera.fecha, ESTATUSPX.NOMBRE,ESTATUSPX.ROWGUID, P.ROWMDTE

order by P.RECORDID

GO


PR_PACIENTECRONOGRAMA 'CAID-SD'
