 

select S.FECHAINI AS FECHAATENCION,  P.FULLNAME AS NOMBRE, P.RECORDID -- ,D.SELECTIVAALIMENTOS 
-- INTO #TMP 
from vPacienteTodos P   
	INNER JOIN HCL00000 M ON  M.REFGUID = P.ROWGUID AND M.ROWSGXID = P.ROWSGXID
 	INNER JOIN HCL00004 D ON D.ROWSGXID = M.ROWSGXID  AND D.ACTGUID = M.ROWGUID  
	INNER JOIN SMX00500 S ON S.REFGUID = P.ROWGUID AND S.ROWSGXID = P.ROWSGXID
	INNER JOIN SMX00300 E ON S.TERID = E.ROWGUID AND S.ROWSGXID = E.ROWSGXID 
	INNER JOIN SMX30013 ES ON ES.ROWGUID = S.ORIGENID  AND ES.ROWSGXID = S.ROWSGXID

where P.ROWSGXID = 'CAID-SD' AND P.RECORDID > 0
 AND D.SELECTIVAALIMENTOS = 1
-- AND M.ESTADO = 'F'
and p.PREDIAGNOSTICO = 'A00A2CDA-7D61-4E4A-A95A-7B5DE484422D' --TEA 
  AND DATEPART(YEAR,S.FECHAINI ) IN (2017,2018)
   and S.CITAESTATUS = 4
ORDER BY  P.FULLNAME--M.ROWCDTE

-- U = 2675

select * from PAX00700  -- diagnosticos frecuentes


 
 

  